name: Combine YAML

on:
  push:
    branches:
      - action-test

jobs:
  combine:
    runs-on: ubuntu-latest

    steps:
      - name: Combine YAML
        uses: brown-ccv/gh-actions/combine-yml@action-combine-yml
